; PlatformIO Project Configuration File for SIH 26008 ESP32 Node
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D SCHEMA_VERSION=\"1.0\"
